Custom theme PRA-57
Code-the-Dream-School/dd-prac-team1-front pull request #24
Opened 2023-08-08 18:55 UTC by ElenaGor8

## One Line Description
Added colors and fonts to Chakra default theme

## Requirements

_What this code should do_
extend Chakra default theme

## Notes

_Any additional info_

## Test Steps

_Instructions on how to test the changes_

## UI/UX Outcome

_Attach a screenshot here_

## Checklist

- The Linear ID is in the PR title
- My code follows best practices
- Documentation is included where needed

2023-08-09 04:17 UTC, AnnaPestova1 approved these changes

2023-08-10 23:50 UTC, rebekahcallkacz requested changes
Congrats on your first PR 🎉 

I see the expected changes and they look great! Most of my comments have to do with code you included that you don't actually need (and thus should remove).

2023-08-10 23:50 UTC, rebekahcallkacz commented on package.json
> +    "@fontsource/raleway": "^5.0.7",
NON-BLOCKING: Are we actually using these fonts?

2023-08-10 23:50 UTC, rebekahcallkacz commented on src/CustomTheme.js
BLOCKING: This file should be converted to TypeScript - `CustomTheme.ts`

2023-08-10 23:50 UTC, rebekahcallkacz commented on Fonts/Poppins/OFL.txt
BLOCKING: You shouldn't need this folder `Fonts` or anything in it. The fonts should load in correctly with just the info you included in `CustomTheme.js`

2023-08-10 23:50 UTC, rebekahcallkacz commented on package.json
> +    "@fontsource/raleway": "^5.0.7",
I don't see them being used anywhere and the new fonts show up without me installing these.

2023-08-10 23:50 UTC, rebekahcallkacz commented on src/index.tsx
> +import { ChakraProvider, extendTheme } from "@chakra-ui/react";
BLOCKING: You do not need to import `extendTheme` here

2023-08-13 21:47 UTC, ElenaGor8 commented
made changes as per Rebecca's requests

2023-08-14 02:47 UTC, AnnaPestova1 approved these changes

2023-08-15 01:06 UTC, rebekahcallkacz approved these changes
This looks great! 

I just want to point out (to make sure it's clear, not because it's an issue), that you've only redefined `gray.900` and `gray.50`. If any of the other grays are used, they are going to be the Chakra defaults.

2023-08-15 17:53 UTC, ElenaGor8 commented
I have our gray defined as  brandGray: "#f4f4eb"
900 to 50 I should probably delete, as they are from default theme, right?

2023-08-15 18:23 UTC, rebekahcallkacz commented
> I have our gray defined as brandGray: "#f4f4eb" 900 to 50 I should probably delete, as they are from default theme, right?

If you're not using them, then, yes, I'd remove them!

2023-08-15 19:04 UTC, merged