Devops/contact PRA-129
Code-the-Dream-School/dd-prac-team1-front pull request #31
Opened 2023-08-14 01:19 UTC by SvetlanaBeynik

## One Line Description
Contact

## Requirements

_What this code should do_

## Notes

_Any additional info_

## Test Steps

_Instructions on how to test the changes_

## UI/UX Outcome
<img width="433" alt="image" src="https://github.com/Code-the-Dream-School/dd-prac-team1-front/assets/116919138/6f5c84a6-466a-49b5-8fc6-9ffefe0a95e3">

_Attach a screenshot here_

## Checklist

- The Linear ID is in the PR title
- My code follows best practices
- Documentation is included where needed

2023-08-14 21:12 UTC, AnnaPestova1 approved these changes

2023-08-15 01:49 UTC, rebekahcallkacz requested changes
Mostly looks good - just a few nitpicky comments!

2023-08-15 01:49 UTC, rebekahcallkacz commented on src/components/Contact.tsx
> +                  <Link as={RouterLink} to="/contact">
BLOCKING: Why does the submit button send you to the contact page? You're already on the contact page.

2023-08-15 01:49 UTC, rebekahcallkacz commented on src/components/Contact.tsx
> +                <Button variant="outline" size="lg">
NON-BLOCKING: Maybe this should wait for a later PR, but you want the button to be disabled until after all of the required fields are filled out.

2023-08-15 01:49 UTC, rebekahcallkacz commented on src/components/Contact.tsx
> +                <FormLabel>NAME</FormLabel>
BLOCKING: Mockup has these labels as not in all capitals: `Name` instead of `NAME`, etc.

2023-08-15 01:49 UTC, rebekahcallkacz commented on src/components/Contact.tsx
Similar comment as in other places (that does not need to be dealt with in this PR) that the header/navbar/menu should display on this page also and include all of the options on other pages if the user is logged in.

2023-08-15 15:04 UTC, SvetlanaBeynik commented
New design 
<img width="1341" alt="image" src="https://github.com/Code-the-Dream-School/dd-prac-team1-front/assets/116919138/ce50022d-1c94-4c45-ac74-8c7b7679cf6a">

2023-08-18 02:32 UTC, rebekahcallkacz approved these changes
Looks good to me!

2023-08-18 02:32 UTC, rebekahcallkacz commented on src/components/Contact.tsx
> +import { Link as RouterLink } from "react-router-dom";
NON-BLOCKING: Go ahead and remove this unused import.

2023-08-18 14:53 UTC, AnnaPestova1 commented
before merging new structure of document merging this branch

2023-08-18 14:53 UTC, merged