Dev/teampage PRA-156
Code-the-Dream-School/dd-prac-team1-front pull request #49
Opened 2023-08-22 16:49 UTC by ElenaGor8

## One Line Description
Created Our Team page, also made footer stick to bottom, changed buttons on homepage and contact page to solid green

## Requirements

_What this code should do_

Our Team page shows 6 team members, their images and short "about" text, each member card is clickable to their personal github pages.
Footer should show in the bottom of the pages throughout the app.
footer icons click out to corresponding webpages.
footer nav buttons styled and properly routed.
Buttons changed to solid green in Homepage and Contact pages

## Notes

_Any additional info_

## Test Steps

_Instructions on how to test the changes_

## UI/UX Outcome

_Attach a screenshot here_
![our team](https://github.com/Code-the-Dream-School/dd-prac-team1-front/assets/109550788/6bdd00d8-bca6-4079-9d93-d38cea616c95)

## Checklist

- The Linear ID is in the PR title
- My code follows best practices
- Documentation is included where needed

2023-08-23 00:57 UTC, AnnaPestova1 approved these changes
We have the well behave footer now! Great! I like all here

2023-08-23 09:34 UTC, AnnaSolovykh approved these changes
LGTM!

2023-08-25 18:08 UTC, Ekaterina-Bondareva requested changes
Great job! Love how the page looks like! Please fix one line of code (GitHub link).

2023-08-25 18:08 UTC, Ekaterina-Bondareva commented on src/components/Layout/OurTeam.tsx
> +    githubUrl: "https://github.com/AigulYe"
Could you please fix the link. This link is not work. I suppose the correct one is: `https://github.com/AigulY`

2023-08-25 23:47 UTC, rebekahcallkacz reviewed
Not sure if you want to address this in this PR, but the spacing is off on the Add Recipe page. The footer is slightly hidden on my screen.

2023-08-25 23:52 UTC, rebekahcallkacz reviewed
I might use the term "Front End Developer" and "Back End Developer" (or Engineer instead of developer) instead of just "Front-end" and "Back-end". You usually put a person's "title" instead of just what area they're in.

You'll also want to italicize that title/role to separate it from names - see [this example](https://zelusanalytics.com/).

2023-08-25 23:53 UTC, rebekahcallkacz approved these changes
LGTM other than the link that Kate already pointed out.

2023-08-28 03:04 UTC, ElenaGor8 commented
Made changes to OurTeam page and Footer for responsiveness, added mentors' cards, adjusted height of the Add recipe page, corrected Aigul's gihub link

2023-08-28 15:31 UTC, AnnaPestova1 approved these changes

2023-08-30 00:45 UTC, Ekaterina-Bondareva approved these changes
LGTM! Good job!

2023-08-30 01:04 UTC, merged