Dev/responsive pages part1 (PRA-187)
Code-the-Dream-School/dd-prac-team1-front pull request #63
Opened 2023-08-28 23:52 UTC by AnnaPestova1

## One Line Description
responsive saved recipe page and responsive single recipe page
## Requirements

_What this code should do_
added breakpoints for response design
## Notes

_Any additional info_

## Test Steps

_Instructions on how to test the changes_

## UI/UX Outcome

_Attach a screenshot here_

## Checklist

- The Linear ID is in the PR title
- My code follows best practices
- Documentation is included where needed

2023-08-30 17:36 UTC, ElenaGor8 approved these changes
looks good!

2023-08-31 00:56 UTC, Ekaterina-Bondareva requested changes
Great job! Just a couple of comments:

1. Could you please fix page title to align it to the center of the page?
2. Could you please fix the size of alt image text (make it smaller)
3. Could you please try to implement what all text should be inside the box? 
<img width="506" alt="Снимок экрана 2023-08-30 в 20 53 59" src="https://github.com/Code-the-Dream-School/dd-prac-team1-front/assets/107886514/8b6bacde-58e2-48dd-b735-a7c07a440cfd">

2023-08-31 01:09 UTC, Ekaterina-Bondareva commented
Single recipe page looks great as it is. Maybe just if you will have a time also align title to the center. 
<img width="387" alt="Снимок экрана 2023-08-30 в 21 10 46" src="https://github.com/Code-the-Dream-School/dd-prac-team1-front/assets/107886514/e7c9cc1b-3b66-4855-ad7c-3b27ea151e2c">

2023-08-31 03:14 UTC, AnnaPestova1 commented
> Great job! Just a couple of comments:
> 
> 1. Could you please fix page title to align it to the center of the page?

The title is on the center on the Grid with recipes

> 2. Could you please fix the size of alt image text (make it smaller)

fixed the card sizes and text here is Image alt

> 3. Could you please try to implement what all text should be inside the box?

Done
> 
> <img alt="Снимок экрана 2023-08-30 в 20 53 59" width="506" src="https://user-images.githubusercontent.com/107886514/264504523-8b6bacde-58e2-48dd-b735-a7c07a440cfd.png">

2023-09-01 22:38 UTC, rebekahcallkacz approved these changes
LGTM

2023-09-01 22:38 UTC, rebekahcallkacz commented on src/components/SavedRecipes/SavedRecipesItem.tsx
> +      // maxW={{ base: "175px", md: "200px" }}
NON-BLOCKING: If you don't need these anymore, I'd just delete them. (see line 35 too)

2023-09-02 03:07 UTC, Ekaterina-Bondareva approved these changes

2023-09-02 03:17 UTC, merged