Dev/responsiveness part4 (PRA-198)
Code-the-Dream-School/dd-prac-team1-front pull request #70
Opened 2023-08-31 23:25 UTC by AnnaPestova1

## One Line Description
Fix responsiveness in Navbar and RecipeManual component
## Requirements
we had some issue with search input in Navbar and with manual recipe page on very small screens. 
_What this code should do_

## Notes

_Any additional info_

## Test Steps

_Instructions on how to test the changes_

## UI/UX Outcome

_Attach a screenshot here_

## Checklist

- The Linear ID is in the PR title
- My code follows best practices
- Documentation is included where needed

2023-09-01 17:44 UTC, ElenaGor8 approved these changes
LGTM

2023-09-03 16:43 UTC, AnnaSolovykh approved these changes
Well done! Looks great!

2023-09-05 23:28 UTC, Ekaterina-Bondareva requested changes
Good job!  Just couple things to fix: 

1. Search in NavBar hidden a bit:
<img width="502" alt="Снимок экрана 2023-09-05 в 19 29 42" src="https://github.com/Code-the-Dream-School/dd-prac-team1-front/assets/107886514/c4387a7a-63e6-4826-8b09-e2046a5b13bf">
2. Placeholder in  Tags input is not completely visible.
<img width="502" alt="Снимок экрана 2023-09-05 в 19 29 42" src="https://github.com/Code-the-Dream-School/dd-prac-team1-front/assets/107886514/8c9b393f-fe86-474a-a107-efec56f76a54">

2023-09-05 23:34 UTC, Ekaterina-Bondareva approved these changes

2023-09-06 00:18 UTC, merged