Dev/search in planner (PRA-101)
Code-the-Dream-School/dd-prac-team1-front pull request #88
Opened 2023-09-05 22:50 UTC by AnnaPestova1

## One Line Description
added search to Planner
## Requirements

_What this code should do_

## Notes

_Any additional info_

## Test Steps

_Instructions on how to test the changes_

## UI/UX Outcome

_Attach a screenshot here_

## Checklist

- The Linear ID is in the PR title
- My code follows best practices
- Documentation is included where needed

2023-09-06 01:09 UTC, rebekahcallkacz requested changes
There seems to be a bug - when I filter my recipes and drag one of the filtered recipes onto the planner, a different recipe shows up.

Initial list: [lemon chicken, strawberry smooth, sriracha lime chicken, pb banana smoothie]
Filtered list: [lemon chicken, sriracha lime chicken]

In the initial list, the recipe I want is the 3rd recipe (sriracha lime chicken). In the filtered list, it is the 2nd recipe. When I drag and drop sriracha chicken from the filtered list, the strawberry smoothie (which is the second item in the original list but does not show up in the filtered list) is what shows up in the planner.

Let me know if you can't replicate the bug and need a video!

2023-09-06 01:20 UTC, AnnaPestova1 commented on src/utils/types.tsx
> +export interface PlannerRecipe extends SavedRecipe {
<img width="579" alt="image" src="https://github.com/Code-the-Dream-School/dd-prac-team1-front/assets/106414157/b874b258-c491-48a0-81e4-3b55649486ae">
yep.

2023-09-06 01:21 UTC, AnnaPestova1 commented on src/components/SingleRecipePage/SingleRecipePage.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
Thank you! I will remove it

2023-09-06 16:38 UTC, AnnaSolovykh approved these changes

2023-09-06 21:11 UTC, AnnaPestova1 commented
> There seems to be a bug - when I filter my recipes and drag one of the filtered recipes onto the planner, a different recipe shows up.
> 
> Initial list: [lemon chicken, strawberry smooth, sriracha lime chicken, pb banana smoothie] Filtered list: [lemon chicken, sriracha lime chicken]
> 
> In the initial list, the recipe I want is the 3rd recipe (sriracha lime chicken). In the filtered list, it is the 2nd recipe. When I drag and drop sriracha chicken from the filtered list, the strawberry smoothie (which is the second item in the original list but does not show up in the filtered list) is what shows up in the planner.
> 
> Let me know if you can't replicate the bug and need a video!

I hope I fixed

2023-09-07 02:04 UTC, rebekahcallkacz approved these changes
Tested again and it works now

I successfully:
- added a recipe to the planner
- removed a recipe from the planner
- added a recipe to the planner from a filtered version of the recipes
- cleared all recipes
- added all ingredients to shopping list

Great job!

2023-09-08 15:46 UTC, rebekahcallkacz reviewed
I think you can merge this one after it passes the checks and whenever you're ready!

2023-09-08 18:37 UTC, merged